export const GET_BAYILER_FROM_API = "GET_BAYILER_FROM_API";
export const EDIT_BAYILER_ON_API = "EDIT_BAYILER_ON_API";
export const ADD_BAYI_TO_API = "ADD_BAYI_TO_API";
export const GET_MUSTERILER_FROM_API = "GET_MUSTERILER_FROM_API";
export const GET_PROFILLER_FROM_API = "GET_PROFILLER_FROM_API";
export const GET_DIGER_MALZEMELER_FROM_API = "GET_DIGER_MALZEMELER_FROM_API";
export const GET_CAMLAR_FROM_API = "GET_CAMLAR_FROM_API";
export const GET_SISTEMLER_FROM_API = "GET_SISTEMLER_FROM_API";
export const GET_PROJELER_FROM_API = "GET_PROJELERR_FROM_API";
export const GET_SELECTED_FROM_PROJELERTABLE = "GET_SELECTED_FROM_PROJELERTABLE";
export const ADD_SIPARISLER_FROM_API = "ADD_SIPARISLER_FROM_API"
export const GET_SIPARISLER_FROM_API = "GET_SIPARISLER_FROM_API"
export const DELETE_SIPARIS_FROM_API = "DELETE_SIPARIS_FROM_API"
export const GET_SIPARIS_BY_ID_SUCCESS = "GET_SIPARIS_BY_ID_SUCCESS";
export const EDIT_SIPARIS_SUCCESS = "EDIT_SIPARIS_SUCCESS";
export const GET_SIPARISLER_SUCCESS = "GET_SIPARISLER_SUCCESS";
export const DELETE_SIPARIS_SUCCESS = "DELETE_SIPARIS_SUCCESS";
export const GET_SIPARISLER_FOR_TABLE_SUCCESS = "GET_SIPARISLER_FOR_TABLE_SUCCESS";
export const ADD_BAYI_SUCCESS = "ADD_BAYI_SUCCESS";
export const EDIT_BAYI_SUCCESS = "EDIT_BAYI_SUCCESS";
export const DELETE_BAYI_SUCCESS = "DELETE_BAYI_SUCCESS";
export const SYSTEM_VARIANTS_OF_SYSTEM = "SYSTEM_VARIANTS_OF_SYSTEM";
export const GET_PROJE_FROM_API = "GET_PROJE_FROM_API"
export const FULL_VARIANT_OF_SYSTEM = "FULL_VARIANT_OF_SYSTEM";
export const GET_PROJE_REQUIREMENTS_FROM_API = "GET_PROJE_REQUIREMENTS_FROM_API"
export const GET_PROFIL_IMAGE_FROM_API = "GET_PROFIL_IMAGE_FROM_API"
export const GET_PROFILE_BOYALAR_FROM_API = "GET_PROFILE_BOYALAR_FROM_API"
export const GET_GLASS_BOYALAR_FROM_API = "GET_GLASS_BOYALAR_FROM_API"
export const GET_SYSTEM_VARIANTS_FROM_API = "GET_SYSTEM_VARIANTS_FROM_API"
export const LOGIN_REQUEST  = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS  = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE  = 'LOGIN_FAILURE'
export const LOAD_USER      = 'LOAD_USER'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'
export const LOGOUT = 'LOGOUT'
export const GET_KUMANDALAR_FROM_API ='GET_KUMANDALAR_FROM_API'
export const ADD_KUMANDA_TO_API = 'ADD_KUMANDA_TO_API'
// === PDF Title ===
export const UPDATE_PDF_TITLE_REQUEST        = "UPDATE_PDF_TITLE_REQUEST";
export const UPDATE_PDF_TITLE_SUCCESS        = "UPDATE_PDF_TITLE_SUCCESS";
export const UPDATE_PDF_TITLE_FAILURE        = "UPDATE_PDF_TITLE_FAILURE";

export const GET_PDF_TITLE_BY_KEY_REQUEST    = "GET_PDF_TITLE_BY_KEY_REQUEST";
export const GET_PDF_TITLE_BY_KEY_SUCCESS    = "GET_PDF_TITLE_BY_KEY_SUCCESS";
export const GET_PDF_TITLE_BY_KEY_FAILURE    = "GET_PDF_TITLE_BY_KEY_FAILURE";

// === PDF Brand ===
export const UPDATE_PDF_BRAND_REQUEST        = "UPDATE_PDF_BRAND_REQUEST";
export const UPDATE_PDF_BRAND_SUCCESS        = "UPDATE_PDF_BRAND_SUCCESS";
export const UPDATE_PDF_BRAND_FAILURE        = "UPDATE_PDF_BRAND_FAILURE";

export const GET_PDF_BRAND_BY_KEY_REQUEST    = "GET_PDF_BRAND_BY_KEY_REQUEST";
export const GET_PDF_BRAND_BY_KEY_SUCCESS    = "GET_PDF_BRAND_BY_KEY_SUCCESS";
export const GET_PDF_BRAND_BY_KEY_FAILURE    = "GET_PDF_BRAND_BY_KEY_FAILURE";

// === Proforma (Project Code Rule) ===
export const UPDATE_PROFORMA_RULE_REQUEST    = "UPDATE_PROFORMA_RULE_REQUEST";
export const UPDATE_PROFORMA_RULE_SUCCESS    = "UPDATE_PROFORMA_RULE_SUCCESS";
export const UPDATE_PROFORMA_RULE_FAILURE    = "UPDATE_PROFORMA_RULE_FAILURE";
export const GET_BRAND_IMAGE_SUCCESS = "GET_BRAND_IMAGE_SUCCESS";
